# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install
      - run: yarn install

  deploy:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: bundle install
      - run: yarn install
      - run: git config user.email "saulopefa@gmail.com"
      - run: git config user.name "Pau Perez"
      - run: ./deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
